//articles
export const ARTICLES_LOAD = 'ARTICLES_LOAD';
export const ARTICLES_LOAD_START = 'ARTICLES_LOAD_START';
export const ARTICLES_LOAD_SUCCESS = 'ARTICLES_LOAD_SUCCESS';
export const ARTICLES_LOAD_ERROR = 'ARTICLES_LOAD_ERROR';
export const ARTICLES_SAVE = 'ARTICLES_SAVE';
export const ARTICLE_CREATE = 'ARTICLE_CREATE';
export const ARTICLE_DELETE = 'ARTICLE_DELETE';
export const ARTICLE_COMMENT_CREATE = 'ARTICLE_COMMENT_CREATE';
export const ARTICLE_COMMENT_DELETE = 'ARTICLE_COMMENT_DELETE';
